#!/usr/bin/env python3
"""Extract the housing parameters from the PCB.

Usage: python3 fan-housing/extract_geometry.py

Writes board_params.scad next to this script. All dimensions come from pcbnew,
not from the text format of the .kicad_pcb: transforming footprint rotations by
hand has cost this project two wrong wirings once already, and a connector
mirrored by 90 degrees shows up on the finished print, not before.

Coordinates: origin at the lower left corner of the board outline, X to the
right, Y up - the way you look at the populated side.
"""
import os
import pcbnew

HERE = os.path.dirname(os.path.abspath(__file__))
PCB = os.path.join(HERE, "..", "fan-controller", "fan-controller.kicad_pcb")
OUT = os.path.join(HERE, "board_params.scad")
LW = 0.05            # half the Edge.Cuts line width, included in the bounding box

# Parts whose footprint area the housing needs
WANTED = ["U1", "J1", "J2", "J3", "J4", "J5", "C1", "U2"]

board = pcbnew.LoadBoard(PCB)
box = board.GetBoardEdgesBoundingBox()
x0, ytop = box.GetLeft(), box.GetBottom()
mm = lambda v: round(v / 1e6, 3)

L = mm(box.GetWidth()) - 2 * LW
W = mm(box.GetHeight()) - 2 * LW

def bbox(ref):
    for f in board.GetFootprints():
        if f.GetReference() != ref:
            continue
        cy = f.GetCourtyard(pcbnew.F_CrtYd).BBox()
        if cy.GetWidth() == 0:
            cy = f.GetBoundingBox(False, False)
        return (mm(cy.GetLeft() - x0) - LW, mm(cy.GetRight() - x0) - LW,
                mm(ytop - cy.GetBottom()) - LW, mm(ytop - cy.GetTop()) - LW)
    raise KeyError(ref)

# Antenna keep-out: zones are in absolute coordinates, no rotation involved
ant = None
for i in range(board.GetAreaCount()):
    z = board.GetArea(i)
    if not z.GetIsRuleArea():
        continue
    b = z.GetBoundingBox()
    ant = (mm(b.GetLeft() - x0) - LW, mm(b.GetRight() - x0) - LW,
           mm(ytop - b.GetBottom()) - LW, mm(ytop - b.GetTop()) - LW)

with open(OUT, "w") as f:
    f.write("// GENERATED by fan-housing/extract_geometry.py\n"
            "// Do not edit by hand - after a board change, run the script again.\n\n")
    f.write(f"board_l = {L};   // X, long side\n")
    f.write(f"board_w = {W};   // Y, short side\n\n")
    for ref in WANTED:
        xa, xb, ya, yb = bbox(ref)
        f.write(f"{ref}_x = [{xa}, {xb}];  {ref}_y = [{ya}, {yb}];\n")
    if ant:
        f.write(f"\nantenna_x = [{ant[0]}, {ant[1]}];  "
                f"antenna_y = [{ant[2]}, {ant[3]}];\n")

print(f"{OUT} written:  board {L} x {W} mm")
for ref in WANTED:
    xa, xb, ya, yb = bbox(ref)
    print(f"  {ref:3}  X {xa:6.2f}..{xb:6.2f}   Y {ya:6.2f}..{yb:6.2f}")
if ant:
    print(f"  antenna zone  X {ant[0]:.2f}..{ant[1]:.2f}  Y {ant[2]:.2f}..{ant[3]:.2f}")
